name: CI

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: experimental-features = nix-command flakes
    - run: |
        nix develop --command bash << 'EOF'
          set -euxo pipefail
          just
          cargo test
          git diff --exit-code
        EOF
