name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3
    - uses: tree-sitter/setup-action@eeb902ac2f1be576edc296309872cf476a209b7f # v2
      with:
        install-lib: false
    - run: just
    - run: cargo test
    - run: git diff --exit-code
